version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-billow_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/chepetime/billow:v0.1.5
    init: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://billow:billow-password@db:5432/billow?schema=public
    restart: on-failure

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: billow
      POSTGRES_USER: billow
      POSTGRES_PASSWORD: billow-password
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    restart: on-failure
